spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.217.129:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
eureka:
  client:
    service-url:
      defualtZone: http://localhost:8761/eureka/
server:
  port: 8082